version: '3'

services:

  sample:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - 3001:3000
    # environment:
    #   - CHOKIDAR_USEPOLLING=true