version: '3.7'

services:

  sample:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '/app/build'
    ports:
      - 3001:3000
    # environment:
    #   - CHOKIDAR_USEPOLLING=true